### ISSUE TITLE
error when using Android-GUI-Injector to inject

### ISSUE THREAD

**Issue by raviruia522** [reveny/Android-ImGui-Mod-Menu#2]
I want to use Android-GUI-Injector to inject the .so library into the game. when i run it. Android-GUI-Injector does not report an error, but the game does not appear in the imGui menu, and the mod functions also do not work. Can you check it again? Because editing apk is not suitable for some games

**Comment by reveny** [comment]
Please provide the logcat, without that I cannot do much to fix it.
